kind: pipeline
name: default

steps:
  - name: docker_build
    image: plugins/docker
    settings:
      username: aakashsinghalmd01
      password: 'Welcome@md'
      repo: cubeiocorp/jersy_1_19_emp
      tags:
        - ${DRONE_COMMIT}-${DRONE_BRANCH}
        - ${DRONE_BRANCH}-latest
    dockerfile: employee-service/
    resources:
      requests:
        cpu: 0.1
        memory: "1500Mi"
      limits:
        cpu: 1
        memory: "1500Mi"

trigger:
  branch:
  - add/drone
